DESCRIBE TABLE USERPROFILES;
DESCRIBE TABLE VIEWERSHIP;

SELECT * FROM USERPROFILES LIMIT 5;
SELECT * FROM VIEWERSHIP LIMIT 5;

-- Create a new, cleaner table
CREATE OR REPLACE TABLE VIEWERSHIP_CLEAN AS
SELECT 
    USERID,                    -- Who watched
    CHANNEL2,                  -- What channel they watched
    RECORDDATE2,               -- Original date/time
    DURATION2,                 -- How long they watched
    
    -- Make a proper date/time (add 2 hours for South Africa time)
    DATEADD(HOUR, 2, TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS WATCH_DATETIME,
    
    -- Just the date (like 2025-10-15)
    DATE(DATEADD(HOUR, 2, TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI'))) AS WATCH_DATE,
    
    -- What day was it? (Monday, Tuesday, etc.)
    DAYNAME(DATEADD(HOUR, 2, TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI'))) AS DAY_NAME,
    
    -- What hour? (0-23, like 14 = 2pm)
    HOUR(DATEADD(HOUR, 2, TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI'))) AS HOUR_OF_DAY,
    
    -- Duration in minutes (easier to understand than HH:MM:SS)
    (HOUR(TO_TIME(DURATION2)) * 60 + MINUTE(TO_TIME(DURATION2))) AS MINUTES_WATCHED
    
FROM VIEWERSHIP;

--How many people watched TV?
SELECT COUNT(DISTINCT USERID) AS TOTAL_USERS
FROM VIEWERSHIP_CLEAN;

--What's the total viewing time?
SELECT 
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES,
    SUM(MINUTES_WATCHED) / 60 AS TOTAL_HOURS
FROM VIEWERSHIP_CLEAN;

--What are the top 10 most popular channels?
SELECT 
    CHANNEL2 AS CHANNEL_NAME,
    COUNT(*) AS NUMBER_OF_VIEWS,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY CHANNEL2
ORDER BY TOTAL_MINUTES DESC;


--Which day of the week do people watch the most?
SELECT 
    DAY_NAME,
    COUNT(*) AS NUMBER_OF_VIEWS,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY DAY_NAME
ORDER BY TOTAL_MINUTES DESC;

--What time of day do people watch TV?
SELECT 
    HOUR_OF_DAY,
    COUNT(*) AS NUMBER_OF_VIEWS,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY HOUR_OF_DAY
ORDER BY HOUR_OF_DAY;


--How much does each person watch?
SELECT 
    USERID,
    COUNT(*) AS TIMES_WATCHED,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES,
    AVG(MINUTES_WATCHED) AS AVERAGE_MINUTES_PER_SESSION
FROM VIEWERSHIP_CLEAN
GROUP BY USERID
ORDER BY TOTAL_MINUTES DESC;

--Age Buckets

SELECT 
    CASE 
        WHEN UP.AGE < 18 THEN 'Under 18'
        WHEN UP.AGE BETWEEN 18 AND 34 THEN '18–34'
        WHEN UP.AGE BETWEEN 35 AND 49 THEN '35–49'
        WHEN UP.AGE >= 50 THEN '50+' 
        ELSE 'Unknown'
    END AS AGE_GROUP,
    COUNT(DISTINCT VC.USERID) AS USERS,
    SUM(VC.MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN VC
JOIN USERPROFILES UP ON VC.USERID = UP.USERID
GROUP BY AGE_GROUP
ORDER BY TOTAL_MINUTES DESC;


--Gender Consumption
SELECT 
    UP.GENDER,
    COUNT(DISTINCT VC.USERID) AS USERS,
    SUM(VC.MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN VC
JOIN USERPROFILES UP ON VC.USERID = UP.USERID
GROUP BY UP.GENDER
ORDER BY TOTAL_MINUTES DESC;

--Province
SELECT 
    UP.PROVINCE,
    COUNT(DISTINCT VC.USERID) AS USERS,
    SUM(VC.MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN VC
JOIN USERPROFILES UP ON VC.USERID = UP.USERID
GROUP BY UP.PROVINCE
ORDER BY TOTAL_MINUTES DESC;


--low consumption Days
SELECT 
    WATCH_DATE,
    DAY_NAME,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY WATCH_DATE, DAY_NAME
ORDER BY TOTAL_MINUTES ASC;

--Genre-level Analysis
SELECT 
    CASE 
        WHEN CHANNEL2 IN ('KIDS1', 'KIDS2') THEN 'Kids'
        WHEN CHANNEL2 IN ('SPORTS1', 'SPORTS2') THEN 'Sports'
        WHEN CHANNEL2 IN ('DRAMA1', 'DRAMA2') THEN 'Drama'
        WHEN CHANNEL2 IN ('NEWS1', 'NEWS2') THEN 'News'
        ELSE 'Other'
    END AS GENRE,
    COUNT(*) AS SESSIONS,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY GENRE
ORDER BY TOTAL_MINUTES DESC;

--Viewing Freqency
SELECT 
    CASE 
        WHEN TIMES_WATCHED >= 20 THEN 'Heavy'
        WHEN TIMES_WATCHED BETWEEN 10 AND 19 THEN 'Moderate'
        ELSE 'Light'
    END AS USER_TYPE,
    COUNT(*) AS USER_COUNT
FROM (
    SELECT USERID, COUNT(*) AS TIMES_WATCHED
    FROM VIEWERSHIP_CLEAN
    GROUP BY USERID
) AS USER_SESSIONS
GROUP BY USER_TYPE;


--Peak Viewing Windows
SELECT 
    DAY_NAME,
    HOUR_OF_DAY,
    SUM(MINUTES_WATCHED) AS TOTAL_MINUTES
FROM VIEWERSHIP_CLEAN
GROUP BY DAY_NAME, HOUR_OF_DAY
ORDER BY TOTAL_MINUTES DESC;

CREATE OR REPLACE TABLE BRIGHTTV_EXPORT AS
SELECT 
    VC.USERID,
    VC.CHANNEL2,
    VC.RECORDDATE2,
    VC.DURATION2,
    VC.WATCH_DATETIME,
    VC.WATCH_DATE,
    VC.DAY_NAME,
    VC.HOUR_OF_DAY,
    VC.MINUTES_WATCHED,
    
    -- Add user profile info
    UP.AGE,
    UP.GENDER,
    UP.PROVINCE
FROM VIEWERSHIP_CLEAN VC
JOIN USERPROFILES UP ON VC.USERID = UP.USERID;

SELECT * FROM BRIGHTTV_EXPORT;



